### ISSUE TITLE
About Missing Data (0 values)

### ISSUE THREAD

**Issue by imethanlee** [MengzhangLI/STFGNN#15]
There is a lot of missing data (those with value 0) in several datasets (such as METR-LA). Did you adopt any interplolation approach (such as linear interplolation) to fill in these missing values?
![an example of missing values in METR-LA](https://user-images.githubusercontent.com/36200682/112792498-2c708d80-9096-11eb-8a64-4a0ac8446cec.png)

**Comment by MengzhangLI** [comment]
> There is a lot of missing data (those with value 0) in several datasets (such as METR-LA). Did you adopt any interplolation approach (such as linear interplolation) to fill in these missing values?
> ![an example of missing values in METR-LA](https://user-images.githubusercontent.com/36200682/112792498-2c708d80-9096-11eb-8a64-4a0ac8446cec.png)

Hi, sorry for late reply.

First of all, the result of this model on METR-LA is wrong because the metric of METR-LA, PEMS-BAY, etc is different from PEMS0X. Sorry for my misleading result on first version on ARXIV.

But I can answer this question: right now most model use masked index to solve many zero/null values in METR-LA and PEMS-BAY. When training, the masked index could skip places of those zeor/null to get loss for back propagation.

For example, you can check it from GraphWaveNet:
https://github.com/nnzhan/Graph-WaveNet/blob/6b162e80c59a1d494809252eca055cff93dc66b1/util.py#L177

Best,

**Comment by imethanlee** [comment]
This helps a lot. Thanks.
