### ISSUE TITLE
New results on LA and BAY datasets

### ISSUE THREAD

**Issue by XinleWu** [MengzhangLI/STFGNN#19]
Hi,

Can you tell me the new results of STFGNN on METR-LA and PeMS-BAY datasets? I'd like to cite your paper, and I should report the performance of STFGNN on these two datasets. If you tell me the results, then I don't need to run your model myself.

Thank you very much!

**Comment by MengzhangLI** [comment]
Hi, thanks for your attention on this paper.

The results on METR-LA and PeMS-BAY in old version is not correct because of different metric between them and PEMS0X datasets. Very very sorry for my stupid mistakes.

I indeed implemented many experiments in February, 2021 and those results are not good thus I directly did not record them because it is no more necessary. So right now I can not show new results.

You can ignore STFGNN on METR-LA and PeMS-BAY. I think GMAN, GraphWaveNet and MTGNN can be better baselines.

Best,

**Comment by XinleWu** [comment]
Thanks for your reply!

I am just worried that I would be argued if I only report the results of STFGNN on PeMS03-08 datasets.

By the way, can you reproduce the results of GMAN on LA and BAY datasets? And I found it's difficult to run GMAN on PeMS03-08 datasets.

Thank you again.

**Comment by MengzhangLI** [comment]
> Thanks for your reply!
> 
> I am just worried that I would be argued if I only report the results of STFGNN on PeMS03-08 datasets.
> 
> By the way, can you reproduce the results of GMAN on LA and BAY datasets? And I found it's difficult to run GMAN on PeMS03-08 datasets.
> 
> Thank you again.

Well, I guess I cannot give you results immediately because I had graduated and these days I'm very busy.

Sorry for my busy schedule but I hope I can discuss with you in the future.

Best,
