### ISSUE TITLE
你好，怎麽去預測輸出对应的流量？

### ISSUE THREAD

**Issue by pengshichang** [MengzhangLI/STFGNN#22]

**Comment by MengzhangLI** [comment]
1. Just use volume variable instead of traffic speed variable.
2. Extending variable from a scalar to a tensor, i.e., certain dimension of the input is no longer 1 but 2.

Personally, I suggest you follow the suggestion 1 because most models do not support the second one. And be careful about data preprocessing especially data input normalization.

Best,

**Comment by pengshichang** [comment]
thanks fro you reply ,i will try it.
